//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG_GameContent.spine {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class witch : global::System.Configuration.ApplicationSettingsBase {
        
        private static witch defaultInstance = ((witch)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new witch())));
        
        public static witch Default {
            get {
                return defaultInstance;
            }
        }
    }
}
